### ISSUE TITLE
In "Pins Over Map" mode, map live-adds rooms without Quill or sitting on bench

### ISSUE THREAD

**Issue by ChrysAlice** [syyePhenomenol/RandoMapMod#11]
Latest version.

Current behavior:
While playing with Pins Over Map mode in Randomizer 4 and having not yet picked up the Quill or Wayward Compass, the map automatically adds rooms as they are entered.

Expected behavior:
Rooms (with their respective checks) should only be added to the map as the player sits on benches and only if they have collected the Quill.

**Comment by syyePhenomenol** [comment]
Hi ChrysAlice,

What you have described isn't the expected behaviour. It is more like the following:
- Map rooms (and their pins) appear for the corresponding map items that have been obtained
- There is always a "base" set of rooms that show per map item even when the player does not have Quill. This is the same as vanilla behaviour.
- If you do have Quill, rooms get added/filled in as soon as you enter their scene. The vanilla behaviour of updating when sitting at a bench is overridden.

However current behaviour is indeed filling in rooms even when Quill isn't obtained. Thanks for the report - I will fix this.

**Comment by syyePhenomenol** [comment]
In the new update (v3.4.0):
Renamed "Pins Over Map" to "Pins Over Area", added new mode "Pins Over Room"
Added "Always Have Quill" toggle. Doesn't affect Full Map or Transition modes. On by default.

This should give more flexibility to Quill and pin behaviour.
